// Auto-generated by `bunbase typegen`
// Do not edit manually - re-run `bunbase typegen` to regenerate.
import 'bunbase'

declare module 'bunbase' {
	interface GeneratedDatabase {
		public: {
			Tables: {
				_migrations: {
					Row: {
						id: number
						name: string
						applied_at: string
					}
					Insert: {
						id?: number
						name: string
						applied_at?: string
					}
					Update: {
						id?: number
						name?: string
						applied_at?: string
					}
					Relationships: []
				}

				action_logs: {
					Row: {
						id: string
						run_id: string
						level: string
						message: string
						meta: unknown | null
						created_at: string
					}
					Insert: {
						id?: string
						run_id: string
						level: string
						message: string
						meta?: unknown | null
						created_at: string
					}
					Update: {
						id?: string
						run_id?: string
						level?: string
						message?: string
						meta?: unknown | null
						created_at?: string
					}
					Relationships: []
				}

				action_runs: {
					Row: {
						id: string
						action_name: string
						module_name: string | null
						trace_id: string
						trigger_type: string
						status: string
						input: unknown | null
						output: unknown | null
						error: string | null
						duration_ms: number
						started_at: string
						created_at: string
					}
					Insert: {
						id: string
						action_name: string
						module_name?: string | null
						trace_id: string
						trigger_type: string
						status: string
						input?: unknown | null
						output?: unknown | null
						error?: string | null
						duration_ms?: number
						started_at: string
						created_at?: string
					}
					Update: {
						id?: string
						action_name?: string
						module_name?: string | null
						trace_id?: string
						trigger_type?: string
						status?: string
						input?: unknown | null
						output?: unknown | null
						error?: string | null
						duration_ms?: number
						started_at?: string
						created_at?: string
					}
					Relationships: []
				}

				job_failures: {
					Row: {
						id: string
						name: string
						data: unknown
						error: string
						attempts: number
						failed_at: string
						trace_id: string | null
					}
					Insert: {
						id: string
						name: string
						data: unknown
						error: string
						attempts: number
						failed_at?: string
						trace_id?: string | null
					}
					Update: {
						id?: string
						name?: string
						data?: unknown
						error?: string
						attempts?: number
						failed_at?: string
						trace_id?: string | null
					}
					Relationships: []
				}

				job_queue: {
					Row: {
						id: string
						name: string
						data: unknown
						status: string
						priority: number
						attempts: number
						max_attempts: number
						run_at: string
						last_error: string | null
						trace_id: string | null
						created_at: string
						updated_at: string
					}
					Insert: {
						id?: string
						name: string
						data?: unknown
						status?: string
						priority?: number
						attempts?: number
						max_attempts?: number
						run_at?: string
						last_error?: string | null
						trace_id?: string | null
						created_at?: string
						updated_at?: string
					}
					Update: {
						id?: string
						name?: string
						data?: unknown
						status?: string
						priority?: number
						attempts?: number
						max_attempts?: number
						run_at?: string
						last_error?: string | null
						trace_id?: string | null
						created_at?: string
						updated_at?: string
					}
					Relationships: []
				}

				kv_store: {
					Row: {
						key: string
						value: unknown
						expires_at: string | null
					}
					Insert: {
						key: string
						value: unknown
						expires_at?: string | null
					}
					Update: {
						key?: string
						value?: unknown
						expires_at?: string | null
					}
					Relationships: []
				}

				sessions: {
					Row: {
						id: string
						user_id: string
						expires_at: string
						created_at: string
					}
					Insert: {
						id?: string
						user_id: string
						expires_at: string
						created_at?: string
					}
					Update: {
						id?: string
						user_id?: string
						expires_at?: string
						created_at?: string
					}
					Relationships: []
				}

				tags: {
					Row: {
						id: string
						name: string
						color: string | null
						created_at: string
					}
					Insert: {
						id?: string
						name: string
						color?: string | null
						created_at?: string
					}
					Update: {
						id?: string
						name?: string
						color?: string | null
						created_at?: string
					}
					Relationships: []
				}

				task_comments: {
					Row: {
						id: string
						task_id: string
						user_id: string
						content: string
						created_at: string
						updated_at: string
					}
					Insert: {
						id?: string
						task_id: string
						user_id: string
						content: string
						created_at?: string
						updated_at?: string
					}
					Update: {
						id?: string
						task_id?: string
						user_id?: string
						content?: string
						created_at?: string
						updated_at?: string
					}
					Relationships: []
				}

				task_tags: {
					Row: {
						task_id: string
						tag_id: string
					}
					Insert: {
						task_id: string
						tag_id: string
					}
					Update: {
						task_id?: string
						tag_id?: string
					}
					Relationships: []
				}

				tasks: {
					Row: {
						id: string
						title: string
						description: string | null
						status: string
						assignee_id: string | null
						created_by: string
						created_at: string
						completed_at: string | null
					}
					Insert: {
						id?: string
						title: string
						description?: string | null
						status?: string
						assignee_id?: string | null
						created_by: string
						created_at?: string
						completed_at?: string | null
					}
					Update: {
						id?: string
						title?: string
						description?: string | null
						status?: string
						assignee_id?: string | null
						created_by?: string
						created_at?: string
						completed_at?: string | null
					}
					Relationships: []
				}

				users: {
					Row: {
						id: string
						email: string
						name: string
						password_hash: string
						created_at: string
					}
					Insert: {
						id?: string
						email: string
						name: string
						password_hash: string
						created_at?: string
					}
					Update: {
						id?: string
						email?: string
						name?: string
						password_hash?: string
						created_at?: string
					}
					Relationships: []
				}
			}
			Views: {}
			Functions: {}
			Enums: {}
			Composites: {}
		}
	}
}
